language: csharp
dotnet: 2.1.4
mono: none
sudo: false
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 0
script:
- dotnet build rsoi_app.sln -c Release
- dotnet test -c Release --no-build rsoi_app_tests/rsoi_app_tests.csproj /p:CollectCoverage=true
  /p:CoverletOutputFormat=opencover
after_script:
- bash <(curl -s https://codecov.io/bash)
deploy: heroku
  api_key:
    secure: UmkVzoFyitUUMSO0HHtqOPBdAfCsCbgVg86Deyki8cgspQegtXLWwGG0A3CBLwtNpSjzhJoQ55N8L3f5c20qaDTmdNZA3KbH3Y1zadqKD04G3LXIAa2L/5sc9b3c2HGqwSC/GNJkbf/hHBFZ5yWk0BySJBzgIxZ3zLvf4oQIfqfHEJwMtcEM5I9LahcMq5kWgBFCDnDhhJk4R5XhVpPcqAevCWe1EGXDemI8RkIb3sTRyJ8WykhBNuBHq7fb19vBg+eeo7+oFCTaKuhbCvE+Tt2JN5kU0g+tUZM6KPfMB+ys7XIQIxMjc6fSqEeIHKxaUEK3hIxUX6cIze51uKT0LmR2VM//fZBG59Vlw1+qmpsXnCCFRiKUPEKKDF7JNyJVS1p2ftF9rO7MELv/ekLOOUw/akn3eYT+RJ198CAl5OEEXDxhobESyqVeN4tXPPNeg3bMQP81v5v7MaMrB9UVmC/Q2nqcFVDBk/iGcbfeXnYygHFklI4vDA8RfWS50UCHo1YPPTVG9gYvaVGbKCiK55ATDxmICje4rXGcbfuwT8KDk2Azg/15KD41pOUByCJS7w7MH9Lk8ljVpo90AbXEI/0QBcdyxnF9bn1glMjXac+Pr4HITxGHmJKlaQoODqxplFY8GhRwU3f7D9y+PkbR3JFiuSBzaXAj4w8PB7teM3I=
