language: csharp
dotnet: 2.1.4
sudo: false
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 0
script: 
  - dotnet build rsoi_app.sln -c Release 
  - dotnet test -c Release --no-build rsoi_app_tests/rsoi_app_tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key:
    secure: 6b12b28b-4f34-4e30-8cef-8297b528bc27
  app: rsoi_app
  on:
    repo: RabbitRu/rsoi_app
