language: csharp
dotnet: 2.1.4
mono: none
sudo: required
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 0

script:
- dotnet build rsoi_app.sln -c Release
- dotnet test -c Release --no-build rsoi_app_tests/rsoi_app_tests.csproj 

before_deploy:
  - cd rsoi_app
  - git push https://rabbitru:rabbit87666@rsoi-app-travis.scm.azurewebsites.net:443/rsoi-app-travis.git --force

deploy:
  provider: azure_web_apps
  skip_cleanup: true  
  verbose: true
  username: rabbitru       # If AZURE_WA_USERNAME isn't set
  password: rabbit87666   # If AZURE_WA_PASSWORD isn't set
  site: rsoi-app-travis      # If AZURE_WA_SITE isn't set