language: csharp
dotnet: 2.1.4
mono: none
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 0

install:
 - dotnet restore

script:
- dotnet build rsoi_app.sln -c Release
- dotnet test -c Release --no-build rsoi_app_tests/rsoi_app_tests.csproj /p:CollectCoverage=true
  /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - cd rsoi_app

deploy:
  provider: azure_web_apps
  skip_cleanup: true  
  verbose: true
  username: rabbitru       # If AZURE_WA_USERNAME isn't set
  password: $azure_wa_password   # If AZURE_WA_PASSWORD isn't set
  site: rsoi-app-travis      # If AZURE_WA_SITE isn't set