language: csharp
dotnet: 2.1.4
mono: none
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 0

script:
- dotnet build rsoi_app.sln -c Release
- dotnet test -c Release --no-build rsoi_app_tests/rsoi_app_tests.csproj 

before_deploy:
  - cd rsoi_app

deploy:
  provider: azure_web_apps
  skip_cleanup: true  
  verbose: true
  username: rsoi-app-travis\$rsoi-app-travis       # If AZURE_WA_USERNAME isn't set
  password: nTm7ocYg2vGYATd9ghBGe5E01jHQpSPG1iQ2hLBj5nY9zkR2k6gw3NpGYZ1c   # If AZURE_WA_PASSWORD isn't set
  site: rsoi-app-travis      # If AZURE_WA_SITE isn't set